### PR TITLE
refactor(l2): rename operator into proposer

### PR DESCRIPTION
**Pull request by fborello-lambda**
**Motivation**

We want to have a different proper name for the `operator` mod inside the `l2` crate.

**Description**

Rename `operator` into `proposer`.

### CODE REVIEW

**Review by ilitteri — CHANGES_REQUESTED** [review]
Rename it to `proposer` instead of `sequencer` as it is a more descriptive name (we've discarded naming this as `sequencer` as this component does much more than just sequencing).

We also need to rename the L1 contract from `OnChainOperator` -> `OnChainProposer`.

**Review by ilitteri — CHANGES_REQUESTED** [review]
Rename it to `proposer` instead of `sequencer` as it is a more descriptive name (we've discarded naming this as `sequencer` as this component does much more than just sequencing).

We also need to rename the L1 contract from `OnChainOperator` -> `OnChainProposer`.

**Comment by fborello-lambda** [comment]
Working on it

**Review by ilitteri — APPROVED** [review]
LGTM

**Pull request merged**
